### ISSUE TITLE
normalize.py - no right trimming?

### ISSUE THREAD

**Issue by ppawliczek** [ga4gh/vmc-python#1]
I think that you need right trimming also at the beginning of normalization.

I would add ((3, 6), "CG") to tests (it should result in ((4,5),""))

https://github.com/ga4gh/vmc-python/blob/f519f61cf2f0f010f9beacff23e931a0d2268417/vmc/normalize.py#L117

**Comment by reece** [comment]
Thanks @ppawliczek! Good catch.
